/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author sam
 */
public class Datos extends javax.swing.JFrame {

    /**
     * Creates new form Datos
     */
    public Datos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_main = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_datos = new javax.swing.JTable();
        txt_edad = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_insertar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_main.setBackground(new java.awt.Color(254, 254, 254));
        pn_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Edad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_datos);
        if (tb_datos.getColumnModel().getColumnCount() > 0) {
            tb_datos.getColumnModel().getColumn(0).setResizable(false);
            tb_datos.getColumnModel().getColumn(1).setResizable(false);
            tb_datos.getColumnModel().getColumn(2).setResizable(false);
            tb_datos.getColumnModel().getColumn(3).setResizable(false);
        }

        pn_main.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 500, 460));
        pn_main.add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 180, 50));
        pn_main.add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 180, 50));
        pn_main.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, 50));
        pn_main.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 180, 50));

        jLabel1.setText("Edad");
        pn_main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 90, 40));

        jLabel2.setText("Cedula");
        pn_main.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 40));

        jLabel3.setText("Nombre");
        pn_main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, 40));

        jLabel4.setText("Apellido");
        pn_main.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 90, 40));

        btn_insertar.setBackground(new java.awt.Color(39, 113, 136));
        btn_insertar.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btn_insertar.setForeground(new java.awt.Color(254, 254, 254));
        btn_insertar.setText("Insertar");
        pn_main.add(btn_insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 140, 50));

        getContentPane().add(pn_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_insertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel pn_main;
    public javax.swing.JTable tb_datos;
    public javax.swing.JTextField txt_apellido;
    public javax.swing.JTextField txt_cedula;
    public javax.swing.JTextField txt_edad;
    public javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
